### ISSUE TITLE
pika potential version error in amqptopicsend

### ISSUE THREAD

**Issue by michael-conway** [angrygoat/DE-Reference#32]
[xdci-service@x-irods msiExecCmd_bin]$ ./amqptopicsend.py "xxxxxxhost" 5672  "user"  "password" false  "data-object.mod"  "{\"author\":{\"name\":\"rods\",\"zone\":\"xdciRenci\"},\"entity\":\"/xdciRenci/home/rods/test/ipc-amqp.re\",\"creator\":{\"name\":\"rods\",\"zone\":\"xdciRenci\"},\"size\":801,\"type\":\"generic\"}"
Traceback (most recent call last):
  File "./amqptopicsend.py", line 29, in <module>
    auto_delete=ephemeral)
TypeError: exchange_declare() got an unexpected keyword argument 'type'
[xdci-service@x-irods msiExecCmd_bin]$ ./amqptopicsend.py "xxxxxxxxx.renci.org" 5672  "xxxxuser"  "xxxpassword" false  "data-object.mod"  "{\"author\":{\"name\":\"rods\",\"zone\":\"xdciRenci\"},\"entity\":\"/xdciRenci/home/rods/test/ipc-amqp.re\",\"creator\":{\"name\":\"rods\",\"zone\":\"xdciRenci\"},\"size\":801}"
Traceback (most recent call last):
  File "./amqptopicsend.py", line 29, in <module>
    auto_delete=ephemeral)
TypeError: exchange_declare() got an unexpected keyword argument 'type'

**Comment by michael-conway** [comment]
```python


#!/usr/bin/env python
import sys
import pika

host = sys.argv[1]
port = int(sys.argv[2])
user = sys.argv[3]
password = sys.argv[4]
ephemeral = sys.argv[5].lower() == 'true'  # Indicates if the exchange is only temporary (for testing)
key = sys.argv[6]
body = sys.argv[7]

exchange='irods'
credentials = pika.PlainCredentials(user, password)

connection = pika.BlockingConnection(
	pika.ConnectionParameters(
			host=host,
			port=port,
			credentials=credentials
	)
)

channel = connection.channel()

channel.exchange_declare(exchange=exchange,
                         type='topic',
                         durable=(not ephemeral),
                         auto_delete=ephemeral)

channel.basic_publish(exchange=exchange,
                      routing_key=key,
                      body=body,
                      properties=pika.BasicProperties(
                          delivery_mode = 2,
                      ))

connection.close()



```

**Comment by michael-conway** [comment]
line 29 switch to 'exchange_type'

```python

#!/usr/bin/env python
import sys
import pika

host = sys.argv[1]
port = int(sys.argv[2])
user = sys.argv[3]
password = sys.argv[4]
ephemeral = sys.argv[5].lower() == 'true'  # Indicates if the exchange is only temporary (for testing)
key = sys.argv[6]
body = sys.argv[7]

exchange='irods'
credentials = pika.PlainCredentials(user, password)

connection = pika.BlockingConnection(
	pika.ConnectionParameters(
			host=host,
			port=port,
			credentials=credentials
	)
)

channel = connection.channel()

channel.exchange_declare(exchange=exchange,
                         exchange_type='topic',
                         durable=(not ephemeral),
                         auto_delete=ephemeral)

channel.basic_publish(exchange=exchange,
                      routing_key=key,
                      body=body,
                      properties=pika.BasicProperties(
                          delivery_mode = 2,
                      ))

connection.close()



```

**Comment by michael-conway** [comment]
also check playbook for libmsisetavu (update that doc) and make sure the so is moved to /usr/lib/irods/plugins/microservices

**Comment by donsizemore** [comment]
These should be done. Check behind me?
