### ISSUE TITLE
elasticsearch issues running tag queries

### ISSUE THREAD

**Issue by michael-conway** [angrygoat/DE-Reference#4]
click on an entered tag on a data object to do a search, gives a de message about search not being available

[2016-08-24 10:20:56,074][DEBUG][action.search.type       ] [node-dfc-de-esearch] [data][0], node[Wv3-S_ZWQU2cq0MEkvF-nA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@1a307c28] lastShard [true]
org.elasticsearch.search.SearchParseException: [data][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must":{"terms":{"id":["6aa89388-6957-11e6-a0b8-005056a2d298"]}},"filter":{"term":{"creator":"testde2#dfc1"}}}},"_source":false}]]
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:649)
    at org.elasticsearch.search.SearchService.createContext(SearchService.java:511)
    at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:483)
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:252)
    at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:206)
    at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:203)
    at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:517)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [data] [bool] query does not support [filter]
    at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:88)
    at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:238)
    at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:342)
    at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:268)
    at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:263)
    at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:633)
    ... 9 more

**Comment by michael-conway** [comment]
more info on error, appears to be in the mappings, per https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#field-conflicts

[2016-08-24 13:44:08,958][DEBUG][action.admin.indices.mapping.put] [node-dfc-de-esearch] failed to put mappings on indices [[data]], type [tag]
org.elasticsearch.index.mapper.MergeMappingException: Merge failed with failures {[object mapping [targets] can't be changed from non-nested to nested, mapper [id] has different index values, mapper [id] has different tokenize values, mapper [id] has different index_analyzer, mapper [creator] has different index values, mapper [creator] has different tokenize values, mapper [creator] has different index_analyzer, mapper [dateModified] of different type, current_type [long], merged_type [date], mapper [value] has different index_analyzer, mapper [dateCreated] of different type, current_type [long], merged_type [date]]}
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$5.execute(MetaDataMappingService.java:546)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:309)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[2016-08-24 15:38:04,879][DEBUG][action.search.type       ] [node-dfc-de-esearch] [data][1], node[o5yy_lmlQ8CGcj7s649JHw], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@20e53ccb] lastShard [true]
org.elasticsearch.search.SearchParseException: [data][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"must":{"terms":{"id":["83e8613e-6957-11e6-a3c1-005056a2d298"]}},"filter":{"term":{"creator":"testde2#dfc1"}}}},"_source":false}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:649)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:511)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:483)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:252)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:206)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:203)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [data] [bool] query does not support [filter]
        at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:88)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:238)
        at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:342)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:268)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:263)
        at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:633)
        ... 9 more
